dist: trusty
sudo: false
language: cpp
compiler: gcc

before_script:
  - sudo apt-get install -y libsndfile1-dev libxrender1 libsoil1 libx11-dev libx11-6 libxrandr2 x11-common libxrandr-dev libudev-dev libopenal-dev

script:
  - ./console build